### ISSUE TITLE
chickennugget error

### ISSUE THREAD

**Issue by Mansonjr** [PenguScript/qb-chickenfactory#2]
Hi! 

When integrating shared items, there's a mistake.

	-- Chicken Factory Shop
	['chickennuggets'] 			    	 = {['name'] = 'chickennuggets', 	

But in code: 

TriggerServerEvent('QBCore:Server:AddItem', "chickennugget", math.random(6, 12))
                    			TriggerEvent("inventory:client:ItemBox", QBCore.Shared.Items["chickennugget"], "add")

Also found some variables too with the customer-receipt over client/main.lua

I did workarround with naming item in shared to chickennugget and customer-receipt,

Great plugin by the way!! good effort!
Thank you for your collaboration.

**Comment by PenguScript** [comment]
oops. Got ya!
